vechicleapp/urls.py
from django.urls import path
from .import views
app_name='vechicleapp'


urlpatterns = [
    path('',views.index,name='index'),
    path('vechicle/<int:vechicle_id>/', views.detail, name='detail'),
    path('add/', views.add_vechicle, name='add_vechicle'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

vechicleproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("vechicleapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vechicleapp/models.py
from django.db import models

# Create your models here.
class Vechicle(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    img=models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

vechicleapp/views.py
from django.shortcuts import render,redirect
from .models import Vechicle
from .form import VechicleForm

# Create your views here.
def index(request):
    vechicle=Vechicle.objects.all()
    context={
        'vechicle_list':vechicle
    }
    return render(request,'index.html',context)

def detail(request,vechicle_id):
    vechicle=Vechicle.objects.get(id=vechicle_id)
    return render(request,'detail.html',{'vechicle':vechicle})

def add_vechicle(request):
    if request.method=="POST":
        name=request.POST.get('name', )
        desc = request.POST.get('desc', )
        img = request.FILES['img']
        vechicle=Vechicle(name=name,desc=desc,img=img)
        vechicle.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    vechicle=Vechicle.objects.get(id=id)
    form=VechicleForm(request.POST or None,request.FILES,instance=vechicle)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'vechicle':vechicle})
def delete(request,id):
    if request.method=='POST':
        vechicle=Vechicle.objects.get(id=id)
        vechicle.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter your vechicle name"><br>
  <input type="text" name="desc" placeholder="Enter your vechicle description"><br>
  <input type="file" name="img"><br>
  <input type="submit"><br>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online vechicle Showroom
      <a  href="base.html">Add </a>
  </a>

</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST">
    {%csrf_token %}
    Are you want to delete this vechicle?
    <input type="submit">

</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{vechicle.img.url}}" width="300" height="300">
        </div>

<div class="col-md-6">
    <h2>{{vechicle.name}}</h2>>
    <h4>{{vechicle.desc}}</h4>

    <a class="btn btn-warning" href= "{% url 'vechicleapp:update' vechicle.id %}">update</a>
    <a class="btn btn-danger" href= "{% url 'vechicleapp:delete' vechicle.id %}">Delete</a>

</div>
    </div>
</div>

{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}



<div class="container">
    <div class="row">
        {% for i in vechicle_list %}
        <div class="col-md-3">
            <div class="card" style="width: 15rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200" height="250" sp>
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'vechicleapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>

  </div>
</div>
        </div>
        {% endfor %}

    </div>

</div>

{% endblock %}